version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rmq_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - rmq_network
  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python consumer.py'
  #   depends_on:
  #     - db

volumes:
  postgres_data:
networks:
  rmq_network:
    external: true