version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  rabbitmq:
    image: rabbitmq:management
    container_name: rmq
    ports:
      - "5672:5672"  # AMQP connection (Required for pika)
      - "15672:15672"  # Web UI (Optional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: